title: James Loper
email: james@hux.com
description: Personal site of James Loper
baseurl: ""
url: "https://jamesloper.com"
twitter_username: jamesloper
github_username: jamesloper
excerpt_separator: <!--more-->
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
permalink: /:title
include: [ ".well-known" ]
highlighter: rouge
