title: James Loper
email: james@hux.com
description: > # this means to ignore newlines until "baseurl:"
  Personal site of James Loper
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.jamesloper.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jamesloper
github_username:  jamesloper

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

permalink: /:title
include: [".well-known"]
highlighter: rouge
